name: Software Testing Labs CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Junit test with Gradle
        run: ./gradlew test
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            build/reports/tests/
            build/test-results/
      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jacoco-report
          path: |
            build/reports/jacoco/test/html/
            build/reports/jacoco/jacocoTestReport.xml
      - name: Generate Allure report
        run: |
          ./gradlew clean test
          ./gradlew allureReport

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: |
            build/allure-results/
            build/reports/allure-report/

      - name: Publish Allure test Report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: build/reports/allure-report
          destination_dir: .