name: Software Testing Labs CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  JAVA_VERSION: '21'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Build project
        run: ./gradlew assemble

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Run tests
        run: ./gradlew test
      - name: Generate reports
        run: |
          ./gradlew jacocoTestReport
          ./gradlew allureReport
          ./gradlew spotbugsMain spotbugsTest
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: build/reports/tests/test/
      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: |
            build/reports/jacoco/test/html/
            build/reports/jacoco/jacocoTestReport.xml
      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: |
            build/allure-results/
            build/reports/allure-report/
      - name: Upload SpotBugs reports
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-reports
          path: |
            build/reports/spotbugs/main.html
            build/reports/spotbugs/test.html
            build/reports/spotbugs/main.xml
            build/reports/spotbugs/test.xml

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history